######################################################################
# Automatically generated by qmake (3.0) ?? 2? 13 21:04:16 2015
######################################################################

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = MathGame

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp notshow.cpp timeandover.cpp

OTHER_FILES += \
    icons.rc
RC_FILE = icons.rc
